module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-empty": [2, "never"],
    "scope-enum": [
      2,
      "always",
      [
        "cli",
        "code",
        "stack",
        "config",
        "providers",
        "github",
        "gitlab",
        "tests",
        "stability",
        "docs",
        "help",
        "guide",
        "deps",
        "build",
        "ci",
        "release",
        "upgrade",
        "tooling",
        "shell",
        "completions",
        "merge",
        "submit",
        "sync",
        "restack",
        "repair",
        "adopt",
        "absorb",
      ],
    ],
  },
};
